tasks:
  - name: terraform
    # env:
    #   TF_LOG=DEBUG
      # user_uuid = "e328f4ab-b99f-421c-84c9-4ccea042c7d1"   
      # token = "9b49b3fb-b8e9-483c-b703-97ba88eef8e0"
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_cli
  
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_aws_cli
  - name: sinatra
    before: |
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform